- module: apt
  hosts: all
  params:
    - apt:
        name: apache2
        state: "present"  # Remplacez par "absent" pour désinstaller le paquet

- module: service
  hosts: all
  params:
    - service_status:
        name: apache2
        state: "stop"  # Remplacez par l'état souhaité (started, restarted, stopped, enabled, disabled)

- module: copy
  hosts: all
  params:
    - copy:
        src: "./test"
        dest: "./rep/"
        backup: true

- module : command
  hosts : all
  params:
    - command:
      command:
        echo "test" > /tmp/dummy-file |
        cat /tmp/dummy-file