- name: APT
  hosts: all
  tasks:
    - apt_package:
        name: apache2
        state: "present"  # Remplacez par "absent" pour désinstaller le paquet

- name: Service
  hosts: all
  tasks:
    - service_status:
        name: apache2
        state: "start"  # Remplacez par l'état souhaité (started, restarted, stopped, enabled, disabled)

- name: Copy
  hosts: all
  tasks:
  - copy:
      src: "./test"
      dest: "./rep/"
      backup: true
