- name: APT
  hosts: all
  tasks:
    - apt_package:
        name: apache2
        state: "present"  # Remplacez par "absent" pour désinstaller le paquet
      register: result
    - debug:
        var: result

- name: Service
  hosts: all
  tasks:
    - service_status:
        name: apache2
        state: "start"  # Remplacez par l'état souhaité (started, restarted, stopped, enabled, disabled)
      register: result
    - debug:
        var: result


- name: Copy
  hosts: all
  params:
    src: "./public"
    dest: "/var/www/website"
    backup: true