- name: APT
  hosts: all
  tasks:
    - apt_package:
        name: nginx
        state: "absent"  # Remplacez par "absent" pour désinstaller le paquet
      register: result
    - debug:
        var: result

- name: Service
  hosts: all
  tasks:
    - service_status:
        name: apache2
        state: "stop"  # Remplacez par l'état souhaité (started, restarted, stopped, enabled, disabled)
      register: result
    - debug:
        var: result

