- module: APT
  hosts: all
  params:
    - apt_package:
        name: apache2
        state: "present"  # Remplacez par "absent" pour désinstaller le paquet

- module: Service
  hosts: all
  params:
    - service_status:
        name: apache2
        state: "stop"  # Remplacez par l'état souhaité (started, restarted, stopped, enabled, disabled)

- module: Copy
  hosts: all
  params:
    - copy:
        src: "./test"
        dest: "./rep/"
        backup: true

- module : command
  hosts : all
  params:
    - command_module:
      command: |
        echo "test" > /tmp/dummy-file
        cat /tmp/dummy-file